# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
    - directory: /
      package-ecosystem: github-actions
      schedule:
          interval: daily
          timezone: Europe/Copenhagen
          time: "12:00"
      open-pull-requests-limit: 25
      labels: []
    - directory: /doc
      package-ecosystem: npm
      schedule:
          interval: daily
          timezone: Europe/Copenhagen
          time: "12:00"
      open-pull-requests-limit: 25
      labels: []
    - directory: /
      package-ecosystem: nuget
      schedule:
          interval: daily
          timezone: Europe/Copenhagen
          time: "12:00"
      open-pull-requests-limit: 25
      labels: []
